# Generated by Django 4.2 on 2023-04-25 04:58

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('employee_no', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='employee number')),
                ('username', models.CharField(max_length=8, unique=True)),
                ('password', models.CharField(max_length=64)),
                ('old_password', models.CharField(max_length=64)),
                ('date_added', models.DateField(default=django.utils.timezone.now)),
                ('date_deleted', models.DateField()),
                ('date_pw_change', models.DateField(verbose_name='date password change')),
                ('login_attempts', models.PositiveSmallIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('role', models.IntegerField(choices=[('1', 'Employee'), ('2', 'Hr Staff'), ('3', 'Hr Admin'), ('4', 'Hr Superadmin'), ('5', 'Developer')], default='1')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
