# Generated by Django 4.2 on 2023-05-18 03:28

import datetime
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import user.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=25)),
                ('branch_address', models.TextField(max_length=50)),
                ('branch_email', models.EmailField(max_length=254)),
                ('branch_contact_number', models.CharField(max_length=15)),
                ('branch_oic', models.CharField(max_length=25)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_deleted', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'TBL_BRANCH_CODE',
            },
        ),
        migrations.CreateModel(
            name='CityMunicipality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'TBL_CITYMUNICIPALITY',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(max_length=25)),
                ('dept_lead', models.CharField(max_length=25)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_deleted', models.DateTimeField(blank=True, null=True)),
                ('dept_branch_code', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='department', to='user.branch')),
            ],
            options={
                'db_table': 'TBL_DEPARTMENT_CODE',
            },
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('div_name', models.CharField(max_length=25)),
                ('div_lead', models.CharField(max_length=25)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_deleted', models.DateTimeField(blank=True, null=True)),
                ('div_branch_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='division', to='user.branch')),
            ],
            options={
                'db_table': 'TBL_DIVISION_CODE',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_no', models.PositiveSmallIntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(9990)])),
                ('first_name', models.CharField(max_length=25)),
                ('middle_name', models.CharField(blank=True, max_length=25, null=True)),
                ('last_name', models.CharField(max_length=25)),
                ('suffix', models.CharField(blank=True, choices=[('sr', 'Sr.'), ('jr', 'Jr.'), ('iii', 'III/Third'), ('iv', 'IV/Fourth'), ('v', 'V/Fifth')], max_length=4, null=True)),
                ('birthday', models.DateField()),
                ('birth_place', models.CharField(blank=True, max_length=50, null=True)),
                ('civil_status', models.CharField(choices=[('S', 'Single'), ('M', 'Married'), ('A', 'Annulled'), ('W', 'Widowed'), ('SE', 'Separated')], max_length=2)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('address', models.TextField(max_length=50)),
                ('provincial_address', models.TextField(blank=True, max_length=50, null=True)),
                ('mobile_phone', models.CharField(max_length=15)),
                ('email_address', models.EmailField(max_length=254)),
                ('date_hired', models.DateField()),
                ('date_resigned', models.DateField(blank=True, null=True)),
                ('approver', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(9990)])),
                ('date_added', models.DateField(auto_now_add=True)),
                ('date_deleted', models.DateField(blank=True, null=True)),
                ('philhealth_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('employee_image', models.ImageField(blank=True, null=True, upload_to=user.models.upload_to, verbose_name='Image')),
                ('bio_id', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9990)])),
                ('branch_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='user.branch')),
                ('city_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='user.citymunicipality')),
                ('department_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='user.department')),
                ('division_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='user.division')),
            ],
            options={
                'db_table': 'TBL_EMPLOYEE_PROFILE',
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holiday_date', models.DateField()),
                ('holiday_description', models.TextField(blank=True, max_length=100, null=True)),
                ('holiday_type', models.CharField(choices=[('SH', 'Special Non-working Holiday'), ('LH', 'Legal Working Holiday')], max_length=5, unique=True)),
                ('holiday_location', models.CharField(choices=[('city', 'City'), ('province', 'Province'), ('national', 'National')], max_length=15)),
            ],
            options={
                'db_table': 'TBL_HOLIDAY_TYPE',
            },
        ),
        migrations.CreateModel(
            name='PayrollGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('payroll_description', models.TextField(blank=True, max_length=75, null=True)),
                ('monthly_frequency', models.PositiveSmallIntegerField(choices=[(1, 'Monthly'), (2, 'Semi-Monthly'), (3, 'Project-Based'), (4, 'Weekly')], validators=[django.core.validators.MaxValueValidator(4)])),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.DateTimeField(blank=True, null=True)),
                ('used_account', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'TBL_PAYROLL_GROUP_CODE',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('description', models.TextField(blank=True, max_length=100, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_deleted', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'TBL_POSITION_CODE',
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'TBL_PROVINCE',
            },
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('description', models.TextField(blank=True, max_length=100, null=True)),
                ('is_approver', models.BooleanField(default=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_deleted', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'TBL_RANK_CODE',
            },
        ),
        migrations.CreateModel(
            name='ScheduleShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('time_in', models.TimeField()),
                ('time_out', models.TimeField()),
                ('grace_period', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('with_overtime', models.BooleanField()),
                ('is_night_shift', models.BooleanField()),
            ],
            options={
                'db_table': 'TBL_SCHEDULE_SHIFT',
            },
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_form', models.CharField(blank=True, max_length=15, null=True)),
                ('tax_description', models.TextField(blank=True, max_length=100, null=True)),
                ('tax_percentage', models.FloatField(blank=True, null=True)),
                ('tax_amount', models.FloatField(blank=True, null=True)),
                ('tin_id', models.CharField(max_length=12)),
                ('payment_frequency', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Semi-Monthly'), (2, 'Monthly'), (3, 'Annual')], null=True, validators=[django.core.validators.MaxValueValidator(4)])),
                ('emp_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.employee', to_field='emp_no')),
            ],
            options={
                'db_table': 'TBL_TAX_CODE',
            },
        ),
        migrations.CreateModel(
            name='SSS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sss_number', models.CharField(max_length=10)),
                ('sss_contribution_month', models.FloatField(blank=True, null=True)),
                ('sss_with_cashloan_amount', models.FloatField(blank=True, null=True)),
                ('sss_rem_cashloan_amount', models.FloatField(blank=True, null=True)),
                ('sss_with_calloan_amount', models.FloatField(blank=True, null=True)),
                ('sss_rem_callloan_amount', models.FloatField(blank=True, null=True)),
                ('emp_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.employee', to_field='emp_no')),
            ],
            options={
                'db_table': 'TBL_SSS_CODE',
            },
        ),
        migrations.CreateModel(
            name='ScheduleDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_datetime', models.DateTimeField()),
                ('sched_dutyin', models.TimeField()),
                ('sched_dutyout', models.TimeField()),
                ('is_processed', models.BooleanField(blank=True, null=True)),
                ('is_current', models.BooleanField(blank=True, null=True)),
                ('emp_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.employee', to_field='emp_no')),
            ],
            options={
                'db_table': 'TBL_SCHED_DAILY',
            },
        ),
        migrations.CreateModel(
            name='Philhealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ph_number', models.CharField(max_length=10)),
                ('ph_contribution_month', models.FloatField(blank=True, null=True)),
                ('ph_category', models.CharField(blank=True, max_length=10, null=True)),
                ('emp_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.employee', to_field='emp_no')),
            ],
            options={
                'db_table': 'TBL_PHILHEALTH_CODE',
            },
        ),
        migrations.CreateModel(
            name='PAGIBIG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagibig_number', models.CharField(max_length=15)),
                ('pagibig_contribution_month', models.FloatField(blank=True, null=True)),
                ('pagibig_with_cloan_amount', models.FloatField(blank=True, null=True)),
                ('pagibig_rem_cloan_amount', models.FloatField(blank=True, null=True)),
                ('pagibig_with_hloan_amount', models.FloatField(blank=True, null=True)),
                ('pagibig_rem_hloan_amount', models.FloatField(blank=True, null=True)),
                ('emp_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.employee', to_field='emp_no')),
            ],
            options={
                'db_table': 'TBL_PAGIBIG_CODE',
            },
        ),
        migrations.CreateModel(
            name='Overtime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cutoff_id', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(9990)])),
                ('ot_date_filed', models.DateTimeField(auto_now_add=True)),
                ('ot_type', models.CharField(choices=[('WD', 'Whole Day Overtime'), ('BD', 'Before Duty-in'), ('AD', 'After Duty-in')], max_length=2)),
                ('ot_remarks', models.TextField(max_length=100)),
                ('ot_date_from', models.DateTimeField()),
                ('ot_date_to', models.DateTimeField()),
                ('ot_approval_status', models.CharField(choices=[('P1', 'Pending'), ('P2', 'Pending2'), ('APD', 'Approved'), ('DIS', 'Disapproved')], max_length=3)),
                ('ot_reason_disapproval', models.TextField(max_length=100)),
                ('ot_total_hours', models.PositiveSmallIntegerField()),
                ('ot_date_approved1', models.DateTimeField(blank=True, null=True)),
                ('ot_date_approved2', models.DateTimeField(blank=True, null=True)),
                ('emp_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ot', to='user.employee', to_field='emp_no')),
            ],
            options={
                'db_table': 'TBL_OVERTIME_APP',
            },
        ),
        migrations.CreateModel(
            name='OBT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cutoff_id', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(9990)])),
                ('obt_date_filed', models.DateTimeField(auto_now_add=True)),
                ('obt_type', models.CharField(max_length=20)),
                ('obt_location', models.TextField(max_length=50)),
                ('obt_remarks', models.TextField(max_length=100)),
                ('obt_date_from', models.DateTimeField()),
                ('obt_date_to', models.DateTimeField()),
                ('obt_approval_status', models.CharField(choices=[('P1', 'Pending'), ('P2', 'Pending2'), ('APD', 'Approved'), ('DIS', 'Disapproved')], max_length=3)),
                ('obt_reason_disapproval', models.TextField(blank=True, max_length=50, null=True)),
                ('obt_total_hour', models.PositiveSmallIntegerField()),
                ('obt_date_approved1', models.DateTimeField(blank=True, null=True)),
                ('obt_date_approved2', models.DateTimeField(blank=True, null=True)),
                ('emp_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obt', to='user.employee', to_field='emp_no')),
            ],
            options={
                'db_table': 'TBL_OBT_APP',
            },
        ),
        migrations.CreateModel(
            name='Leaves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cutoff_id', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(9990)])),
                ('leave_date_filed', models.DateTimeField(auto_now_add=True)),
                ('leave_type', models.CharField(max_length=3)),
                ('leave_remarks', models.TextField(max_length=100)),
                ('leave_date_from', models.DateTimeField()),
                ('leave_date_to', models.DateTimeField()),
                ('leave_approval_status', models.CharField(choices=[('P1', 'Pending'), ('P2', 'Pending2'), ('APD', 'Approved'), ('DIS', 'Disapproved')], max_length=3)),
                ('leave_reason_disapproval', models.TextField(blank=True, max_length=100, null=True)),
                ('leave_total_hours', models.PositiveSmallIntegerField()),
                ('leave_date_approved1', models.DateTimeField(blank=True, null=True)),
                ('leave_date_approved2', models.DateTimeField(blank=True, null=True)),
                ('leave_number_days', models.PositiveSmallIntegerField()),
                ('emp_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave', to='user.employee', to_field='emp_no')),
            ],
            options={
                'db_table': 'TBL_LEAVES_APP',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='pagibig_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee', to='user.pagibig'),
        ),
        migrations.AddField(
            model_name='employee',
            name='payroll_group_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.payrollgroup'),
        ),
        migrations.AddField(
            model_name='employee',
            name='position_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='user.position'),
        ),
        migrations.AddField(
            model_name='employee',
            name='rank_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='user.rank'),
        ),
        migrations.AddField(
            model_name='employee',
            name='sssid_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee', to='user.sss'),
        ),
        migrations.AddField(
            model_name='employee',
            name='tax_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee', to='user.tax'),
        ),
        migrations.CreateModel(
            name='DTRSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cutoff_id', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(9990)])),
                ('business_datetime', models.DateTimeField()),
                ('shift_name', models.CharField(choices=[('morning', 'Morning Shift'), ('mid', 'Mid Shift'), ('night', 'Night Shift')], max_length=10)),
                ('date_in', models.DateTimeField()),
                ('date_out', models.DateTimeField()),
                ('sched_timein', models.DateTimeField()),
                ('sched_timeout', models.DateTimeField()),
                ('is_sched_restday', models.BooleanField()),
                ('lunch_out', models.DateTimeField()),
                ('lunch_in', models.DateTimeField()),
                ('overbreak', models.PositiveSmallIntegerField()),
                ('lates', models.PositiveSmallIntegerField()),
                ('adjusted_timein', models.DateTimeField()),
                ('adjusted_timeout', models.DateTimeField()),
                ('total_hours', models.PositiveSmallIntegerField()),
                ('is_paid_leave', models.BooleanField(default=False)),
                ('paid_leave_reason', models.CharField(max_length=50)),
                ('reg_ot_total', models.PositiveSmallIntegerField()),
                ('nd_ot_total', models.PositiveSmallIntegerField()),
                ('pay_period', models.DateTimeField()),
                ('is_computed', models.BooleanField(default=False)),
                ('emp_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dtrsummary', to='user.employee', to_field='emp_no')),
            ],
            options={
                'db_table': 'TBL_DTR_SUMMARY',
            },
        ),
        migrations.CreateModel(
            name='DTR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio_id', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(9990)])),
                ('datetime_bio', models.DateTimeField()),
                ('flag1_in_out', models.BooleanField()),
                ('flag2_lout_lin', models.BooleanField(blank=True, null=True)),
                ('entry_type', models.CharField(blank=True, choices=[('DIN', 'Duty In'), ('DOUT', 'Duty Out'), ('LOUT', 'Lunch Out'), ('LIN', 'Lunch In')], max_length=4, null=True)),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
                ('is_processed', models.BooleanField(default=False)),
                ('sched_timein', models.DateTimeField(blank=True, null=True)),
                ('sched_timeout', models.DateTimeField(blank=True, null=True)),
                ('business_datetime', models.DateTimeField(blank=True, null=True)),
                ('branch_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dtr', to='user.branch')),
                ('emp_no', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dtr', to='user.employee', to_field='emp_no')),
            ],
            options={
                'db_table': 'TBL_DTR_ENTRY',
            },
        ),
        migrations.CreateModel(
            name='Cutoff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co_name', models.CharField(max_length=20)),
                ('co_description', models.TextField(max_length=75)),
                ('co_date', models.DateTimeField()),
                ('co_date_from', models.DateTimeField()),
                ('co_date_to', models.DateTimeField()),
                ('co_is_processed', models.BooleanField()),
                ('credit_date', models.DateTimeField()),
                ('payroll_frequency', models.PositiveSmallIntegerField(choices=[(1, 'Monthly'), (2, 'Semi-Monthly'), (3, 'Project-Based'), (4, 'Weekly')], validators=[django.core.validators.MaxValueValidator(4)])),
                ('division_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.division')),
                ('payroll_group_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.payrollgroup')),
            ],
            options={
                'db_table': 'TBL_CUTOFF_PERIOD_LIST',
            },
        ),
        migrations.AddField(
            model_name='citymunicipality',
            name='province_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citymunicipality', to='user.province'),
        ),
        migrations.CreateModel(
            name='AuditTrail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(max_length=15)),
                ('table_affected', models.CharField(max_length=30)),
                ('action_remarks', models.TextField(max_length=100)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('emp_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audittrail', to='user.employee', to_field='emp_no')),
            ],
            options={
                'db_table': 'TBL_AUDITTRAIL',
            },
        ),
        migrations.CreateModel(
            name='Adjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cutoff_id', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(9990)])),
                ('deducted_amount', models.FloatField()),
                ('added_amount', models.FloatField()),
                ('adjustment_remark', models.TextField(max_length=100)),
                ('adjustment_remark2', models.TextField(max_length=100)),
                ('prepared_by_employee_number', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(9990)])),
                ('approved_by_employee_number', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(9990)])),
                ('is_computed', models.BooleanField(default=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_deleted', models.DateTimeField(blank=True, null=True)),
                ('emp_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustment', to='user.employee', to_field='emp_no')),
            ],
            options={
                'db_table': 'TBL_ADJUSTMENT_ENTRY',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=8, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('role', models.PositiveSmallIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('is_logged_in', models.BooleanField(default=False)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('date_deleted', models.DateField(blank=True, null=True)),
                ('failed_login_attempts', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('last_login', models.DateTimeField(default=datetime.datetime(2023, 1, 1, 0, 0))),
                ('old_password', models.CharField(default='N/A', max_length=128)),
                ('date_password_changed', models.DateField(blank=True, null=True)),
                ('emp_no', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='user.employee', to_field='emp_no')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'TBL_USER',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
