# Generated by Django 4.2 on 2023-05-11 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SSSID',
            new_name='SSS',
        ),
        migrations.AlterField(
            model_name='employee',
            name='tax_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee', to='user.tax'),
        ),
        migrations.AlterModelTable(
            name='sss',
            table='TBL_SSS_CODE',
        ),
    ]
