# Generated by Django 4.2 on 2023-04-25 07:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.PositiveSmallIntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(9990)])),
                ('username', models.CharField(max_length=9)),
                ('password', models.CharField(max_length=128)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date_deleted', models.DateTimeField(blank=True, null=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('failed_login_attempts', models.PositiveSmallIntegerField(default=0)),
                ('old_password', models.CharField(blank=True, max_length=128)),
                ('date_password_change', models.DateTimeField(blank=True, null=True)),
                ('role', models.PositiveSmallIntegerField(choices=[(1, 'employee'), (2, 'hr_staff'), (3, 'hr_admin'), (4, 'hr_superadmin'), (5, 'developer')])),
            ],
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
