# Generated by Django 4.2 on 2023-05-19 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dtrcutoff',
            old_name='is_deleted',
            new_name='date_deleted',
        ),
        migrations.RenameField(
            model_name='leavestype',
            old_name='is_deleted',
            new_name='date_deleted',
        ),
        migrations.RenameField(
            model_name='payrollgroup',
            old_name='is_deleted',
            new_name='date_deleted',
        ),
    ]
