# Generated by Django 4.2 on 2023-05-09 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dtr',
            name='branch_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.branch'),
        ),
    ]
