# Generated by Django 4.2 on 2023-05-18 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DTRCutoff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_datefrom', models.DateField()),
                ('business_dateto', models.DateField()),
                ('hours_total', models.PositiveSmallIntegerField()),
                ('overbreak_total', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('lates_total', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('paid_leaves_total', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('reg_ot_total', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('nd_ot_total', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('sp_holiday_total', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('reg_holiday_total', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('absent_total', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('leaves_type_used', models.CharField(blank=True, max_length=40, null=True)),
                ('is_processed', models.BooleanField()),
                ('is_deleted', models.DateTimeField(blank=True, null=True)),
                ('cutoff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dtrcutoff', to='user.cutoff')),
                ('emp_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dtrcutoff', to='user.employee')),
            ],
            options={
                'db_table': 'TBL_DTR_CUTOFF_SUMMARY',
            },
        ),
    ]
