# Generated by Django 4.2 on 2023-05-24 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cutoff',
            name='co_date_from',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='cutoff',
            name='co_date_to',
            field=models.DateTimeField(),
        ),
    ]
