# Generated by Django 4.2 on 2023-05-10 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagibig',
            name='pagibig_contribution_month',
            field=models.FloatField(),
        ),
    ]
