# Generated by Django 4.2 on 2023-05-08 05:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_leaves_leave_reason_disapproval'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_logged_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dtr',
            name='entry_type',
            field=models.CharField(choices=[('din', 'Duty In'), ('dout', 'Duty Out'), ('lout', 'Lunch Out'), ('lin', 'Lunch In')], max_length=4),
        ),
        migrations.AlterField(
            model_name='dtrsummary',
            name='shift_name',
            field=models.CharField(choices=[('morning', 'Morning Shift'), ('mid', 'Mid Shift'), ('night', 'Night Shift')], max_length=10),
        ),
        migrations.AlterField(
            model_name='employee',
            name='civil_status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Single'), (2, 'Married'), (3, 'Annulled'), (4, 'Widowed'), (5, 'Separated')], default=1, validators=[django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('m', 'Male'), ('f', 'Femals')], max_length=1),
        ),
        migrations.AlterField(
            model_name='employee',
            name='suffix',
            field=models.CharField(blank=True, choices=[('sr', 'Sr.'), ('jr', 'Jr.'), ('iii', 'III/Third'), ('iv', 'IV/Fourth'), ('v', 'V/Fifth')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='holiday_location',
            field=models.CharField(choices=[('city', 'City'), ('province', 'Province'), ('national', 'National')], max_length=15),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='holiday_type',
            field=models.CharField(choices=[('sh', 'Special Non-working Holiday'), ('lh', 'Legal Working Holiday')], max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='leaves',
            name='leave_approval_status',
            field=models.CharField(choices=[('p1', 'Pending'), ('p2', 'Pending2'), ('apd', 'Approved'), ('dis', 'Disapproved')], max_length=3),
        ),
        migrations.AlterField(
            model_name='obt',
            name='obt_approval_status',
            field=models.CharField(choices=[('p1', 'Pending'), ('p2', 'Pending2'), ('apd', 'Approved'), ('dis', 'Disapproved')], max_length=3),
        ),
        migrations.AlterField(
            model_name='overtime',
            name='ot_approval_status',
            field=models.CharField(choices=[('p1', 'Pending'), ('p2', 'Pending2'), ('apd', 'Approved'), ('dis', 'Disapproved')], max_length=3),
        ),
        migrations.AlterField(
            model_name='overtime',
            name='ot_type',
            field=models.CharField(choices=[('wd', 'Whole Day Overtime'), ('bd', 'Before Duty-in'), ('ad', 'After Duty-in')], max_length=2),
        ),
    ]
