# Generated by Django 4.2 on 2023-05-11 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_sssid_sss_alter_employee_tax_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='pagibig_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee', to='user.pagibig'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='sssid_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee', to='user.sss'),
        ),
    ]
