# Generated by Django 4.2 on 2023-05-09 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_dtr_branch_code'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='department',
            table='TBL_DEPARTMENT',
        ),
    ]
