# Generated by Django 4.2 on 2023-05-24 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_cutoff_co_date_from_alter_cutoff_co_date_to'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dtrsummary',
            old_name='date_in',
            new_name='duty_in',
        ),
        migrations.RenameField(
            model_name='dtrsummary',
            old_name='date_out',
            new_name='duty_out',
        ),
        migrations.RenameField(
            model_name='payrollgroup',
            old_name='monthly_frequency',
            new_name='payroll_freq',
        ),
        migrations.RemoveField(
            model_name='cutoff',
            name='co_date',
        ),
        migrations.RemoveField(
            model_name='cutoff',
            name='payroll_frequency',
        ),
        migrations.RemoveField(
            model_name='dtrsummary',
            name='pay_period',
        ),
        migrations.RemoveField(
            model_name='scheduledaily',
            name='is_current',
        ),
        migrations.AddField(
            model_name='scheduledaily',
            name='sched_default',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sched_daily_default', to='user.scheduleshift'),
        ),
        migrations.AlterField(
            model_name='dtrsummary',
            name='adjusted_timein',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dtrsummary',
            name='adjusted_timeout',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dtrsummary',
            name='lunch_in',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dtrsummary',
            name='lunch_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dtrsummary',
            name='overbreak',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
