# Generated by Django 4.2 on 2023-05-11 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_pagibig_pagibig_contribution_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adjustment',
            name='added_amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='adjustment',
            name='deducted_amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='pagibig',
            name='pagibig_rem_cloan_amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='pagibig',
            name='pagibig_rem_hloan_amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='pagibig',
            name='pagibig_with_cloan_amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='pagibig',
            name='pagibig_with_hloan_amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='sssid',
            name='sss_contribution_month',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='sssid',
            name='sss_rem_callloan_amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='sssid',
            name='sss_rem_cashloan_amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='sssid',
            name='sss_with_calloan_amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='sssid',
            name='sss_with_cashloan_amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='tax',
            name='tax_amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='tax',
            name='tax_percentage',
            field=models.FloatField(),
        ),
    ]
