# Generated by Django 4.2 on 2023-04-26 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_delete_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='old_password',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
