# Generated by Django 4.2 on 2023-05-10 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_department_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adjustment',
            name='employee_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustment', to='user.employee', to_field='employee_number'),
        ),
        migrations.AlterField(
            model_name='citymunicipality',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citymunicipality', to='user.province'),
        ),
        migrations.AlterField(
            model_name='department',
            name='branch_code',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='department', to='user.branch'),
        ),
        migrations.AlterField(
            model_name='division',
            name='branch_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='division', to='user.branch'),
        ),
        migrations.AlterField(
            model_name='dtr',
            name='branch_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dtr', to='user.branch'),
        ),
        migrations.AlterField(
            model_name='dtr',
            name='employee_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dtr', to='user.employee', to_field='employee_number'),
        ),
        migrations.AlterField(
            model_name='dtr',
            name='entry_type',
            field=models.CharField(choices=[('DIN', 'Duty In'), ('DOUT', 'Duty Out'), ('LOUT', 'Lunch Out'), ('LIN', 'Lunch In')], max_length=4),
        ),
        migrations.AlterField(
            model_name='dtrsummary',
            name='employee_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dtrsummary', to='user.employee', to_field='employee_number'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='branch_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='user.branch'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='city_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='user.citymunicipality'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='civil_status',
            field=models.CharField(choices=[('S', 'Single'), ('M', 'Married'), ('A', 'Annulled'), ('W', 'Widowed'), ('SE', 'Separated')], max_length=2),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='user.department'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='division_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='user.division'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='user.position'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='rank_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='user.rank'),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='holiday_type',
            field=models.CharField(choices=[('SH', 'Special Non-working Holiday'), ('LH', 'Legal Working Holiday')], max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='leaves',
            name='employee_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave', to='user.employee', to_field='employee_number'),
        ),
        migrations.AlterField(
            model_name='leaves',
            name='leave_approval_status',
            field=models.CharField(choices=[('P1', 'Pending'), ('P2', 'Pending2'), ('APD', 'Approved'), ('DIS', 'Disapproved')], max_length=3),
        ),
        migrations.AlterField(
            model_name='obt',
            name='employee_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obt', to='user.employee', to_field='employee_number'),
        ),
        migrations.AlterField(
            model_name='obt',
            name='obt_approval_status',
            field=models.CharField(choices=[('P1', 'Pending'), ('P2', 'Pending2'), ('APD', 'Approved'), ('DIS', 'Disapproved')], max_length=3),
        ),
        migrations.AlterField(
            model_name='overtime',
            name='employee_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ot', to='user.employee', to_field='employee_number'),
        ),
        migrations.AlterField(
            model_name='overtime',
            name='ot_approval_status',
            field=models.CharField(choices=[('P1', 'Pending'), ('P2', 'Pending2'), ('APD', 'Approved'), ('DIS', 'Disapproved')], max_length=3),
        ),
        migrations.AlterField(
            model_name='overtime',
            name='ot_type',
            field=models.CharField(choices=[('WD', 'Whole Day Overtime'), ('BD', 'Before Duty-in'), ('AD', 'After Duty-in')], max_length=2),
        ),
        migrations.AlterField(
            model_name='user',
            name='employee_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='user.employee', to_field='employee_number'),
        ),
    ]
