# Generated by Django 4.2 on 2023-05-12 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_rename_address_branch_branch_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
    ]
