# Generated by Django 4.2 on 2023-05-24 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_failed_login_attempts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaves',
            name='cutoff_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.cutoff'),
        ),
    ]
