# Generated by Django 4.2 on 2023-05-10 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_adjustment_employee_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
