# Generated by Django 4.2 on 2023-04-26 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_old_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='old_password',
            field=models.CharField(default='Fb1786a206@', max_length=128),
        ),
    ]
