# Generated by Django 4.2 on 2023-05-12 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_date_joined_user_email_user_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='payroll_group_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.payrollgroup'),
        ),
    ]
