# Generated by Django 4.2 on 2023-04-27 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_user_old_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('middle_name', models.CharField(blank=True, max_length=25, null=True)),
                ('last_name', models.CharField(max_length=25)),
                ('suffix', models.CharField(blank=True, max_length=4, null=True)),
                ('birthday', models.DateField()),
                ('gender', models.BooleanField(choices=[(0, 'Female'), (1, 'Male')])),
                ('address', models.CharField(max_length=50)),
                ('provincial_address', models.CharField(blank=True, max_length=50, null=True)),
                ('mobile_phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('approver', models.BooleanField(default=False)),
                ('date_hired', models.DateField()),
                ('date_resigned', models.DateField(blank=True, null=True)),
                ('department_code', models.PositiveSmallIntegerField(choices=[(1, 'Administration'), (2, 'Accounting Department'), (3, 'IT Department'), (4, 'HR Department')])),
                ('division_code', models.PositiveSmallIntegerField(choices=[(1, 'Administration'), (2, 'Accounting Department'), (3, 'IT Department'), (4, 'HR Department')])),
                ('position_code', models.PositiveSmallIntegerField(choices=[(1, 'President'), (2, 'Vice President'), (3, 'Manager'), (4, 'Supervisor'), (5, 'Sales Representative'), (6, 'Customer Service Representative'), (7, 'Marketing Coordinator'), (8, 'Human Resource Coordinator'), (9, 'Accountant'), (10, 'Administrative Assistant'), (11, 'IT Specialist'), (12, 'Graphic Designer'), (13, 'Operations Manager'), (14, 'Project Manager'), (15, 'Production Coordinator'), (16, 'Quality Assurance Specialist'), (17, 'Procurement Specialist'), (18, 'Logistics Coordinator'), (19, 'Business Development Manager'), (20, 'Legal Counsel')])),
                ('rank_code', models.PositiveSmallIntegerField(choices=[(1, 'Junior Level'), (2, 'Mid Level'), (3, 'Senior Level')])),
                ('city_code', models.PositiveSmallIntegerField(verbose_name=((1, 'Caloocan'), (2, 'Las Piñas'), (3, 'Makati'), (4, 'Malabon'), (5, 'Mandaluyong'), (6, 'Manila'), (7, 'Marikina'), (8, 'Muntinlupa'), (9, 'Navotas'), (10, 'Parañaque'), (11, 'Pasay'), (12, 'Pasig'), (13, 'Paterso'), (14, 'Quezon City'), (15, 'San Juan'), (16, 'Taguig'), (17, 'Valenzuela')))),
                ('payroll_group_code', models.PositiveSmallIntegerField(choices=[(1, '20'), (2, '25'), (3, '30')])),
                ('tax_code', models.PositiveSmallIntegerField(choices=[(1, '0%'), (2, '15%'), (3, '20%')])),
                ('sssid_code', models.PositiveSmallIntegerField(choices=[(1, '30%'), (2, '50%'), (3, '70%')])),
                ('philhealth_code', models.PositiveSmallIntegerField(choices=[(1, '30%'), (2, '50%'), (3, '70%')])),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_deleted', models.DateTimeField(blank=True, null=True)),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', to_field='employee_id')),
            ],
            options={
                'db_table': 'TBL_EMPLOYEE_PROFILE',
            },
        ),
    ]
