# Generated by Django 4.2 on 2023-05-12 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_employee_payroll_group_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audittrail',
            name='employee_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audittrail', to='user.employee', to_field='employee_number'),
        ),
    ]
