# Generated by Django 4.2 on 2023-05-24 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_leaves_leave_approver2_empno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overtime',
            name='cutoff_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.cutoff'),
        ),
        migrations.AlterField(
            model_name='overtime',
            name='ot_approver2_empno',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
