# Generated by Django 4.2 on 2023-05-24 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_overtime_cutoff_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dtrsummary',
            name='shift_name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='unaccountedattendance',
            name='ua_description',
            field=models.TextField(blank=True, max_length=75, null=True),
        ),
    ]
