# Generated by Django 4.2 on 2023-05-12 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_audittrail_employee_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dtrsummary',
            old_name='paid_leave',
            new_name='is_paid_leave',
        ),
        migrations.RenameField(
            model_name='dtrsummary',
            old_name='sched_restday',
            new_name='is_sched_restday',
        ),
    ]
