# Generated by Django 4.2 on 2023-05-24 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_dtrsummary_shift_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unaccountedattendance',
            name='ua_description',
            field=models.TextField(max_length=75),
        ),
        migrations.AlterField(
            model_name='unaccountedattendance',
            name='ua_reason_disapproval',
            field=models.TextField(blank=True, max_length=75, null=True),
        ),
    ]
