# Generated by Django 4.2 on 2023-04-27 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_employee_birth_place_employee_civil_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='birth_place',
            field=models.CharField(default='NCR', max_length=25),
        ),
    ]
