# Generated by Django 4.2 on 2023-04-27 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_alter_employee_birth_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditTrail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.PositiveSmallIntegerField(choices=[(1, 'Create'), (2, 'Modify'), (3, 'Delete')])),
                ('table_affected', models.CharField(max_length=100)),
                ('action_remarks', models.CharField(max_length=100)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', to_field='employee_id')),
            ],
            options={
                'db_table': 'TBL_AUDTRAIL',
            },
        ),
    ]
