# Generated by Django 4.2 on 2023-05-25 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_alter_unaccountedattendance_ua_approved_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unaccountedattendance',
            old_name='ua_approved_status',
            new_name='ua_approval_status',
        ),
    ]
