# Generated by Django 4.2 on 2023-04-28 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_employee_branch_code_alter_employee_approver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='pagibig_code',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '30%'), (2, '50%'), (3, '70%')], null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='birth_place',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='suffix',
            field=models.CharField(blank=True, choices=[('jr', 'Jr.'), ('sr', 'Sr.'), ('iii', 'III'), ('iv', 'IV')], max_length=4, null=True),
        ),
    ]
