# Generated by Django 4.2 on 2023-04-28 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_employee_pagibig_code_alter_employee_birth_place_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DTR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('flag1_in_out', models.BooleanField(choices=[(True, 'DOUT'), (False, 'DIN')])),
                ('flag2_lout_lin', models.BooleanField(blank=True, choices=[(True, 'DOUT'), (False, 'DIN')], null=True)),
                ('entry_type', models.CharField(choices=[('din', 'Duty In'), ('dout', 'Duty Out'), ('lin', 'Lunch In'), ('lout', 'Lunch Out')], max_length=4)),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField()),
                ('sched_timein', models.DateTimeField()),
                ('sched_timeout', models.DateTimeField()),
                ('business_datetime', models.DateTimeField()),
                ('branch_code', models.CharField(choices=[('main', 'Main Branch'), ('sub', 'Sub Branch'), ('international', 'International Branch')], default='main', max_length=15)),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', to_field='employee_id')),
            ],
            options={
                'db_table': 'TBL_DTR',
            },
        ),
    ]
