# Generated by Django 4.2 on 2023-04-28 01:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_dtr'),
    ]

    operations = [
        migrations.AddField(
            model_name='dtr',
            name='bio_id',
            field=models.PositiveSmallIntegerField(default=1, unique=True, validators=[django.core.validators.MaxValueValidator(9990)]),
        ),
    ]
