# Generated by Django 4.2 on 2023-05-26 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_alter_dtrsummary_is_sched_restday'),
    ]

    operations = [
        migrations.AddField(
            model_name='dtrsummary',
            name='is_ua',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dtrsummary',
            name='undertime',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
