# Generated by Django 4.2 on 2023-04-28 08:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_dtr_bio_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('province', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'TBL_CITY',
            },
        ),
        migrations.AlterField(
            model_name='audittrail',
            name='action_remarks',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='dtr',
            name='bio_id',
            field=models.PositiveSmallIntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(9990)]),
        ),
    ]
