# Generated by Django 4.2 on 2023-04-28 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_city_alter_audittrail_action_remarks_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='city',
            table='TBL_CITYMUNICIPALITY',
        ),
    ]
