# Generated by Django 4.2 on 2023-05-02 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_alter_city_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='City',
            new_name='CityMunicipality',
        ),
    ]
