# Generated by Django 4.2 on 2023-05-26 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_rename_sss_number_sss_sss_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dtrcutoff',
            old_name='hours_total',
            new_name='total_hours',
        ),
        migrations.AddField(
            model_name='dtrcutoff',
            name='undertime_total',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
