# Generated by Django 4.2 on 2023-05-02 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_rename_city_citymunicipality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citymunicipality',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='citymunicipality',
            name='province',
            field=models.CharField(max_length=40),
        ),
    ]
