# Generated by Django 4.2 on 2023-05-29 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_rename_hours_total_dtrcutoff_total_hours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overtime',
            name='ot_reason_disapproval',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
