# Generated by Django 4.2 on 2023-05-29 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_alter_overtime_ot_reason_disapproval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='suffix',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
