# Generated by Django 4.2 on 2023-05-02 05:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_alter_citymunicipality_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dtr',
            old_name='date_time',
            new_name='date_time_bio',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='employee_id',
            new_name='employee_number',
        ),
        migrations.RemoveField(
            model_name='audittrail',
            name='employee_id',
        ),
        migrations.RemoveField(
            model_name='dtr',
            name='employee_id',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='employee_id',
        ),
        migrations.AddField(
            model_name='audittrail',
            name='employee_number',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='user.user', to_field='employee_number'),
        ),
        migrations.AddField(
            model_name='dtr',
            name='employee_number',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.user', to_field='employee_number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_number',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='user.user', to_field='employee_number'),
        ),
        migrations.AlterField(
            model_name='dtr',
            name='bio_id',
            field=models.PositiveSmallIntegerField(blank=True, null=True, unique=True, validators=[django.core.validators.MaxValueValidator(9990)]),
        ),
    ]
