# Generated by Django 4.2 on 2023-05-02 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_rename_date_time_dtr_date_time_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audittrail',
            name='employee_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', to_field='employee_number'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', to_field='employee_number'),
        ),
    ]
