# Generated by Django 4.2 on 2023-05-30 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_alter_scheduleshift_grace_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dtrsummary',
            name='duty_in',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dtrsummary',
            name='duty_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
