# Generated by Django 4.2 on 2023-05-03 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_alter_audittrail_employee_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='failed_login_attempts',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='DTRSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cutoff_id', models.PositiveSmallIntegerField()),
                ('business_datetime', models.DateTimeField()),
                ('shift_time', models.CharField(choices=[('morning', 'Morning Shift'), ('mid', 'Mid Shift'), ('night', 'Night Shift')], max_length=7)),
                ('date_in', models.DateTimeField()),
                ('date_out', models.DateTimeField()),
                ('sched_timein', models.DateTimeField()),
                ('sched_timeout', models.DateTimeField()),
                ('sched_restday', models.BooleanField()),
                ('lunch_out', models.DateTimeField()),
                ('lunch_in', models.DateTimeField()),
                ('overbreak', models.PositiveSmallIntegerField()),
                ('lates', models.PositiveSmallIntegerField()),
                ('adjusted_time_in', models.DateTimeField()),
                ('adjusted_time_out', models.DateTimeField()),
                ('total_hours', models.PositiveSmallIntegerField()),
                ('paid_leave', models.BooleanField(default=False)),
                ('paid_leave_reason', models.CharField(blank=True, choices=[(1, 'Absent'), (2, 'Vacation Leave'), (3, 'Sick Leave'), (4, 'Maternity Leave'), (5, 'Emergency Leave')], max_length=15, null=True)),
                ('reg_ot_total', models.PositiveSmallIntegerField()),
                ('nd_ot_total', models.PositiveSmallIntegerField()),
                ('ot_approved', models.BooleanField(default=False)),
                ('pay_period', models.DateTimeField()),
                ('is_computed', models.BooleanField(default=False)),
                ('employee_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', to_field='employee_number')),
            ],
            options={
                'db_table': 'TBL_DTR_SUMMARY',
            },
        ),
    ]
