# Generated by Django 4.2 on 2023-05-30 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_alter_dtrsummary_duty_in_alter_dtrsummary_duty_out'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dtrsummary',
            name='sched_timein',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='dtrsummary',
            name='sched_timeout',
            field=models.TimeField(),
        ),
    ]
