# Generated by Django 4.2 on 2023-05-03 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_alter_user_failed_login_attempts_dtrsummary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('description', models.TextField(max_length=100)),
                ('holiday_type', models.CharField(choices=[('SH', 'Special Non-Working Holiday'), ('LH', 'Legal Non-Working Holiday')], max_length=2)),
                ('location', models.CharField(choices=[('city', 'City'), ('province', 'Province'), ('national', 'National')], max_length=10)),
            ],
            options={
                'db_table': 'TBL_HOLIDAY_TYPE',
            },
        ),
    ]
