# Generated by Django 4.2 on 2023-05-04 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_alter_holiday_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'TBL_PROVINCE',
            },
        ),
        migrations.AlterField(
            model_name='holiday',
            name='holiday_type',
            field=models.CharField(choices=[('SH', 'Special Non-Working Holiday'), ('LH', 'Legal Working Holiday')], max_length=2),
        ),
        migrations.AlterField(
            model_name='citymunicipality',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.province'),
        ),
    ]
