# Generated by Django 4.2 on 2023-05-04 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0027_province_alter_holiday_holiday_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OBT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.TextField(max_length=100)),
                ('obt_type', models.CharField(choices=[('client meeting', 'On Client Mettting'), ('on-site', 'On-Site Project'), ('others', 'Others')], max_length=25)),
                ('location', models.CharField(max_length=50)),
                ('remarks', models.TextField(max_length=100)),
            ],
            options={
                'db_table': 'TBL_OBT',
            },
        ),
    ]
