# Generated by Django 4.2 on 2023-06-02 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0027_alter_dtrcutoff_emp_no_alter_employee_civil_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dtrcutoff',
            name='leaves_type_used',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
