# Generated by Django 4.2 on 2023-05-04 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0028_obt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obt',
            name='description',
        ),
        migrations.AddField(
            model_name='obt',
            name='approval_status',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='obt',
            name='date_from',
            field=models.DateTimeField(default=''),
        ),
        migrations.AddField(
            model_name='obt',
            name='date_until',
            field=models.DateTimeField(default=''),
        ),
        migrations.AddField(
            model_name='obt',
            name='reason_disapproval',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='obt',
            name='total_hour',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='obt',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='obt',
            name='location',
            field=models.CharField(default='Pasig', max_length=50),
        ),
        migrations.AlterField(
            model_name='obt',
            name='obt_type',
            field=models.CharField(choices=[('client meeting', 'On Client Mettting'), ('on-site', 'On-Site Project'), ('others', 'Others')], default='others', max_length=25),
        ),
        migrations.AlterField(
            model_name='obt',
            name='remarks',
            field=models.TextField(default='', max_length=100),
        ),
    ]
