# Generated by Django 4.2 on 2023-05-04 05:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0029_remove_obt_description_obt_approval_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obt',
            name='date_from',
            field=models.DateTimeField(default=datetime.datetime(12, 1, 1, 0, 0)),
        ),
        migrations.AlterField(
            model_name='obt',
            name='date_until',
            field=models.DateTimeField(default=datetime.datetime(12, 1, 1, 0, 0)),
        ),
    ]
