# Generated by Django 4.2 on 2023-06-06 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0029_alter_dtrcutoff_leaves_type_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='cutoff',
            name='reg_days_total',
            field=models.PositiveSmallIntegerField(default=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='emp_salary_allowance',
            field=models.FloatField(default=5000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='emp_salary_basic',
            field=models.FloatField(default=20000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='emp_salary_other',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='emp_salary_type',
            field=models.CharField(default='monthly', max_length=7),
            preserve_default=False,
        ),
    ]
