# Generated by Django 4.2 on 2023-06-06 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0030_cutoff_reg_days_total_employee_emp_salary_allowance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_cname', models.CharField(max_length=50)),
                ('run_date', models.DateField(auto_now_add=True)),
                ('accnt_no', models.CharField(max_length=25)),
                ('salary_basic', models.FloatField()),
                ('salary_allowance', models.FloatField()),
                ('salary_other', models.FloatField()),
                ('salary_type', models.CharField(max_length=7)),
                ('gross_pay', models.FloatField()),
                ('work_days_total', models.PositiveSmallIntegerField()),
                ('daily_summary_basic', models.FloatField()),
                ('daily_summary_allowance', models.FloatField()),
                ('daily_summary_other', models.FloatField()),
                ('leaves_amount_a', models.FloatField()),
                ('ot_amount_a', models.FloatField()),
                ('holiday_amount_a', models.FloatField()),
                ('nd_amount_a', models.FloatField()),
                ('lates_amount_d', models.FloatField()),
                ('utime_amount_d', models.FloatField()),
                ('absent_amount_d', models.FloatField()),
                ('tax_amount_d', models.FloatField()),
                ('sss_amount_d', models.FloatField()),
                ('pagibig_amount_d', models.FloatField()),
                ('philhealth_amount_d', models.FloatField()),
                ('cash_advance_amount_d', models.FloatField()),
                ('pagibig_other_d', models.FloatField()),
                ('sss_other_d', models.FloatField()),
                ('insurance_d', models.FloatField()),
                ('other_d', models.FloatField()),
                ('date_deleted', models.DateTimeField(blank=True, null=True)),
                ('emp_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.employee', to_field='emp_no')),
                ('pr_cutoff_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.cutoff')),
            ],
            options={
                'db_table': 'TBL_PAYROLL_RUN',
            },
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_printed', models.BooleanField(blank=True, null=True)),
                ('date_deleted', models.DateTimeField(blank=True, null=True)),
                ('tbl_payroll_run_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.payroll')),
            ],
            options={
                'db_table': 'TBL_PAYSLIP',
            },
        ),
    ]
