# Generated by Django 4.2 on 2023-05-04 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0030_alter_obt_date_from_alter_obt_date_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obt',
            name='approval_status',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='obt',
            name='date_from',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='obt',
            name='date_until',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='obt',
            name='location',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='obt',
            name='obt_type',
            field=models.CharField(choices=[('client meeting', 'On Client Mettting'), ('on-site', 'On-Site Project'), ('others', 'Others')], max_length=25),
        ),
        migrations.AlterField(
            model_name='obt',
            name='remarks',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='obt',
            name='total_hour',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
