# Generated by Django 4.2 on 2023-06-06 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0031_payroll_payslip'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='is_payslip_printed',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Payslip',
        ),
    ]
