# Generated by Django 4.2 on 2023-05-04 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0031_alter_obt_approval_status_alter_obt_date_from_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='obt',
            old_name='date',
            new_name='date_filed',
        ),
        migrations.AddField(
            model_name='obt',
            name='cutoff_id',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='obt',
            name='date_approved1',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obt',
            name='date_approved2',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='obt',
            name='approval_status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Pending'), (1, 'Pending'), (2, 'Approved'), (3, 'Disapproved')]),
        ),
        migrations.AlterModelTable(
            name='obt',
            table='TBL_OBT_ENTRY',
        ),
    ]
