# Generated by Django 4.2 on 2023-06-07 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0032_payroll_is_payslip_printed_delete_payslip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payroll',
            old_name='pagibig_amount_d',
            new_name='pagibigc_amount_d',
        ),
        migrations.RenameField(
            model_name='payroll',
            old_name='pagibig_other_d',
            new_name='philhealthc_amount_d',
        ),
        migrations.RenameField(
            model_name='payroll',
            old_name='sss_amount_d',
            new_name='sssc_amount_d',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='philhealth_amount_d',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='sss_other_d',
        ),
        migrations.RemoveField(
            model_name='tax',
            name='tax_amount',
        ),
        migrations.AddField(
            model_name='employee',
            name='insurance_life',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='other_deductible',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payroll',
            name='net_pay',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payroll',
            name='pagibig_cloan_d',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='payroll',
            name='pagibig_hloan_d',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='payroll',
            name='sss_calloan_d',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='payroll',
            name='sss_cashloan_d',
            field=models.FloatField(default=0),
        ),
    ]
