# Generated by Django 4.2 on 2023-05-04 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0033_obt_employee_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='OvertimeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_filed', models.DateTimeField(auto_now_add=True)),
                ('overtime_type', models.CharField(choices=[('whole day', 'Whole Day Overtime'), ('before duty', 'Before Duty-in'), ('after duty', 'After Duty-in')], max_length=15)),
                ('remarks', models.TextField(max_length=100)),
                ('date_from', models.DateTimeField()),
                ('date_until', models.DateTimeField()),
                ('approval_status', models.PositiveSmallIntegerField(choices=[(0, 'Pending'), (1, 'Pending'), (2, 'Approved'), (3, 'Disapproved')])),
                ('reason_disapproval', models.TextField(max_length=100)),
                ('total_hours', models.PositiveSmallIntegerField()),
                ('cutoff_id', models.PositiveSmallIntegerField(default=0)),
                ('date_approved1', models.DateTimeField(blank=True, null=True)),
                ('date_approved2', models.DateTimeField(blank=True, null=True)),
                ('employee_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', to_field='employee_number')),
            ],
        ),
    ]
