# Generated by Django 4.2 on 2023-05-04 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0034_overtimeentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obt',
            name='approval_status',
            field=models.CharField(choices=[('P1', 'Pending'), ('P2', 'Pending2'), ('APD', 'Approved'), ('DIS', 'Disapproved')], max_length=15),
        ),
        migrations.AlterField(
            model_name='overtimeentry',
            name='approval_status',
            field=models.PositiveSmallIntegerField(choices=[('P1', 'Pending'), ('P2', 'Pending2'), ('APD', 'Approved'), ('DIS', 'Disapproved')]),
        ),
    ]
