# Generated by Django 4.2 on 2023-06-07 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0034_rename_daily_summary_allowance_payroll_daily_salary_allowance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='accnt_no',
            field=models.CharField(default=123456789101112, max_length=25),
            preserve_default=False,
        ),
    ]
