# Generated by Django 4.2 on 2023-05-04 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0035_alter_obt_approval_status_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OvertimeEntry',
            new_name='OvertimeApp',
        ),
        migrations.RenameField(
            model_name='obt',
            old_name='date_until',
            new_name='date_to',
        ),
        migrations.RenameField(
            model_name='overtimeapp',
            old_name='date_until',
            new_name='date_to',
        ),
        migrations.AlterModelTable(
            name='obt',
            table='TBL_OBT_APP',
        ),
        migrations.AlterModelTable(
            name='overtimeapp',
            table='TBL_OVERTIME_APP',
        ),
    ]
