# Generated by Django 4.2 on 2023-06-07 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0036_cashadvance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payroll',
            old_name='absent_amount_d',
            new_name='absent_amount',
        ),
        migrations.RenameField(
            model_name='payroll',
            old_name='holiday_amount_a',
            new_name='reg_holiday_amount_a',
        ),
        migrations.AddField(
            model_name='dtrcutoff',
            name='sp_holiday_total_hours',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payroll',
            name='sp_holiday_amount_a',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
