# Generated by Django 4.2 on 2023-06-09 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0037_rename_absent_amount_d_payroll_absent_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='work_days_total',
            field=models.FloatField(),
        ),
    ]
