# Generated by Django 4.2 on 2023-05-04 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0037_alter_overtimeapp_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='overtimeapp',
            table='TBL_OVERTIME_APP',
        ),
    ]
