# Generated by Django 4.2 on 2023-06-09 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0038_alter_payroll_work_days_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sss',
            old_name='sss_rem_callloan_amount',
            new_name='sss_rem_calloan_amount',
        ),
    ]
