# Generated by Django 4.2 on 2023-06-13 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0039_rename_sss_rem_callloan_amount_sss_sss_rem_calloan_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='accnt_no',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
