# Generated by Django 4.2 on 2023-06-14 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0040_alter_employee_accnt_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowanceEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('tax_rate', models.FloatField(blank=True, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_deleted', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AllowanceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowance_name', models.CharField(max_length=50)),
                ('taxable', models.BooleanField(default=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_deleted', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='employee',
            name='emp_salary_allowance',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='emp_salary_other',
        ),
        migrations.AddField(
            model_name='employee',
            name='ecola',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='TaxCollected',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_rate_used', models.FloatField()),
                ('amount_deducted', models.FloatField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('allowance_entry_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.allowanceentry')),
                ('cutoff_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.cutoff')),
                ('emp_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.employee', to_field='emp_no')),
            ],
        ),
        migrations.AddField(
            model_name='allowanceentry',
            name='allowance_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.allowancetype'),
        ),
        migrations.AddField(
            model_name='allowanceentry',
            name='emp_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.employee', to_field='emp_no'),
        ),
    ]
