# Generated by Django 4.2 on 2023-05-04 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0041_alter_obt_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='obt',
            table='TBL_OBT_APP',
        ),
    ]
