# Generated by Django 4.2 on 2023-06-14 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0041_allowanceentry_allowancetype_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='allowanceentry',
            table='TBL_ALLOWANCE_ENTRY',
        ),
        migrations.AlterModelTable(
            name='allowancetype',
            table='TBL_ALLOWANCE_TYPE',
        ),
        migrations.AlterModelTable(
            name='taxcollected',
            table='TBL_TAX_COLLECTED',
        ),
    ]
