# Generated by Django 4.2 on 2023-05-04 07:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0042_alter_obt_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audittrail',
            name='employee_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.employee', to_field='employee_number'),
        ),
        migrations.AlterField(
            model_name='dtr',
            name='employee_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.employee', to_field='employee_number'),
        ),
        migrations.AlterField(
            model_name='dtrsummary',
            name='employee_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.employee', to_field='employee_number'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_number',
            field=models.PositiveSmallIntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(9990)]),
        ),
        migrations.AlterField(
            model_name='obt',
            name='employee_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.employee', to_field='employee_number'),
        ),
        migrations.AlterField(
            model_name='overtimeapp',
            name='employee_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.employee', to_field='employee_number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='employee_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.employee', to_field='employee_number'),
        ),
    ]
