# Generated by Django 4.2 on 2023-06-15 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0045_remove_taxallowancebracket_frequency_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='taxallowancebracket',
            table='TBL_TAX_ALLOWA_BRACKET',
        ),
    ]
