# Generated by Django 4.2 on 2023-06-15 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0046_alter_taxallowancebracket_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxbasicbracket',
            name='fix_tax_amount',
            field=models.FloatField(default=0),
        ),
    ]
