# Generated by Django 4.2 on 2023-06-15 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0047_taxbasicbracket_fix_tax_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxbasicbracket',
            name='frequency',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
