# Generated by Django 4.2 on 2023-06-16 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0048_alter_taxbasicbracket_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='holiday_type',
            field=models.CharField(choices=[('SH', 'Special Non-working Holiday'), ('LH', 'Legal Working Holiday')], max_length=5),
        ),
    ]
