# Generated by Django 4.2 on 2023-06-21 09:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0049_alter_holiday_holiday_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='cutoff_summary_code',
            field=models.ForeignKey(default=50, on_delete=django.db.models.deletion.CASCADE, to='user.dtrcutoff'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='holiday',
            name='holiday_type',
            field=models.CharField(choices=[('SH', 'Special Non-Working Holiday'), ('LH', 'Legal Working Holiday')], max_length=5),
        ),
        migrations.AlterField(
            model_name='tax',
            name='payment_frequency',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Annual'), (2, 'Monthly'), (3, 'Semi-Monthly')], null=True, validators=[django.core.validators.MaxValueValidator(4)]),
        ),
    ]
