# Generated by Django 4.2 on 2023-06-21 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0050_payroll_cutoff_summary_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagibig',
            name='pagibig_rem_calloan_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pagibig',
            name='pagibig_with_calloan_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payroll',
            name='pagibig_calloan_d',
            field=models.FloatField(default=0),
        ),
    ]
