# Generated by Django 4.2 on 2023-06-22 11:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0051_pagibig_pagibig_rem_calloan_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pay13TH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coverage_from', models.DateTimeField()),
                ('coverage_to', models.DateTimeField()),
                ('total_pay', models.FloatField()),
                ('is_printed', models.BooleanField()),
                ('emp_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.employee', to_field='emp_no')),
            ],
            options={
                'db_table': 'TBL_13TH_MPAY',
            },
        ),
        migrations.CreateModel(
            name='AssetsList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_name', models.CharField(max_length=25)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('model', models.CharField(max_length=4)),
                ('year', models.DateField()),
                ('batch_no', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.TextField(max_length=100)),
                ('remarks', models.TextField(blank=True, max_length=100, null=True)),
                ('quantity', models.PositiveSmallIntegerField()),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.employee', to_field='emp_no')),
            ],
            options={
                'db_table': 'TBL_ASSETS_LIST',
            },
        ),
        migrations.CreateModel(
            name='AssetsAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no_manufacturer', models.CharField(max_length=30)),
                ('serial_no_internal', models.CharField(max_length=30)),
                ('remarks', models.TextField(max_length=100)),
                ('asset_list_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.assetslist')),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignedby', to='user.employee', to_field='emp_no')),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignedto', to='user.employee', to_field='emp_no')),
            ],
            options={
                'db_table': 'TBL_ASSETS_ACCOUNT_LIST',
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_posted', models.DateTimeField()),
                ('is_posted', models.BooleanField()),
                ('expiry_date', models.DateTimeField()),
                ('order_by_no', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(3)])),
                ('message', models.TextField(max_length=300)),
                ('emp_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.employee', to_field='emp_no')),
            ],
            options={
                'db_table': 'TBL_ANNOUNCEMENT_LIST',
            },
        ),
    ]
