# Generated by Django 4.2 on 2023-06-26 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0052_pay13th_assetslist_assetsaccount_announcement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavescredit',
            name='allowed_days',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
