# Generated by Django 4.2 on 2023-06-27 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0053_alter_leavescredit_allowed_days'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AssetsList',
            new_name='AssetsLists',
        ),
        migrations.AlterField(
            model_name='pay13th',
            name='is_printed',
            field=models.BooleanField(default=False),
        ),
    ]
