# Generated by Django 4.2 on 2023-06-29 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0054_rename_assetslist_assetslists_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonusList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('description', models.TextField(max_length=100)),
                ('amount', models.FloatField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'TBL_BONUS_LIST',
            },
        ),
        migrations.AddField(
            model_name='dtrcutoff',
            name='rd_ot_total_hours',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dtrcutoff',
            name='rd_reg_holiday_ot_total_hours',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dtrcutoff',
            name='rd_sp_holiday_ot_total_hours',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dtrsummary',
            name='nd_total_hours',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payroll',
            name='rd_ot_amount_a',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='payroll',
            name='rd_reg_holiday_amount_a',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='payroll',
            name='rd_sp_holiday_amount_a',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='BonusEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_applied', models.BooleanField(default=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='added_by_emp_no', to='user.employee', to_field='emp_no')),
                ('bonus_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.bonuslist')),
                ('cutoff_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.cutoff')),
                ('emp_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.employee', to_field='emp_no')),
            ],
            options={
                'db_table': 'TBL_BONUS_ENTRY',
            },
        ),
    ]
