# Generated by Django 4.2 on 2023-07-04 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0056_scheduledaily_is_restday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleshift',
            name='is_night_shift',
            field=models.BooleanField(default=False),
        ),
    ]
