# Generated by Django 4.2 on 2023-07-07 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0057_alter_scheduleshift_is_night_shift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleshift',
            name='name',
            field=models.CharField(max_length=35),
        ),
    ]
