# Generated by Django 4.2 on 2023-07-07 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0058_alter_scheduleshift_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dtrsummary',
            name='shift_name',
            field=models.CharField(max_length=35),
        ),
    ]
