# Generated by Django 4.2 on 2023-07-07 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0059_alter_dtrsummary_shift_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dtrsummary',
            name='shift_name',
            field=models.CharField(default='RD', max_length=35),
        ),
    ]
