# Generated by Django 4.2 on 2023-07-13 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0060_alter_dtrsummary_shift_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='obt',
            old_name='obt_approver2_empono',
            new_name='obt_approver2_empno',
        ),
        migrations.AlterField(
            model_name='holiday',
            name='holiday_location',
            field=models.CharField(choices=[('City', 'City'), ('Province', 'Province'), ('National', 'National')], max_length=15),
        ),
    ]
