# Generated by Django 4.2 on 2023-07-13 14:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0061_rename_obt_approver2_empono_obt_obt_approver2_empno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rank',
            name='hierarchy',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5)]),
            preserve_default=False,
        ),
    ]
