# Generated by Django 4.2 on 2023-07-13 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0062_rank_hierarchy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaves',
            name='leave_approver1_empno',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='obt',
            name='obt_approver1_empno',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='obt',
            name='obt_date_approved1',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='overtime',
            name='ot_approver1_empno',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='unaccountedattendance',
            name='ua_approver1_empno',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
