# Generated by Django 4.2 on 2023-07-13 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0063_alter_leaves_leave_approver1_empno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaves',
            name='leave_approval_status',
            field=models.CharField(choices=[('P1', 'Pending'), ('P2', 'Pending2'), ('APD', 'Approved'), ('DIS', 'Disapproved')], default='P1', max_length=3),
        ),
        migrations.AlterField(
            model_name='obt',
            name='obt_approval_status',
            field=models.CharField(choices=[('P1', 'Pending'), ('P2', 'Pending2'), ('APD', 'Approved'), ('DIS', 'Disapproved')], default='P1', max_length=3),
        ),
        migrations.AlterField(
            model_name='overtime',
            name='ot_approval_status',
            field=models.CharField(choices=[('P1', 'Pending'), ('P2', 'Pending2'), ('APD', 'Approved'), ('DIS', 'Disapproved')], default='P1', max_length=3),
        ),
        migrations.AlterField(
            model_name='unaccountedattendance',
            name='ua_approval_status',
            field=models.CharField(choices=[('P1', 'Pending'), ('P2', 'Pending2'), ('APD', 'Approved'), ('DIS', 'Disapproved')], default='P1', max_length=3),
        ),
    ]
